# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2993cc7763f03ca51ef6f2cc646fd9a4b3ec3e9ad06eefa286e19fc155fd7f1185aeda1f31abeae461118c1de7b532b14c6329a4ad74e64c10603a9d7d24ef57

test:
  secret_key_base: 366214c7dc4ae285cb02df8a7ac13e765f2b009e0464157c52f4cefdabf1d3e32dfb1ad4adb44ca38a9d20018fda1f7084f57ce5fc94ca6ae311b56bd893f12e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
